package io.github.mojri.hesabyar.ui.theme

import androidx.compose.ui.graphics.Color

// Light Theme Colors
val LightPrimary = Color(0xFF0061A4)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFFD1E4FF)
val LightOnPrimaryContainer = Color(0xFF001D36)
val LightSecondary = Color(0xFF535F70)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightTertiary = Color(0xFF6B5778)
val LightOnTertiary = Color(0xFFFFFFFF)
val LightBackground = Color(0xFFFDFBFF)
val LightSurface = Color(0xFFFFFFFF)
val LightOnBackground = Color(0xFF1B1B1F)
val LightOnSurface = Color(0xFF1B1B1F)
val LightSurfaceVariant = Color(0xFFE1E2EC)
val LightOnSurfaceVariant = Color(0xFF44474E)

// Light Theme - Additional Material 3 Colors
val LightSurfaceBright = Color(0xFFFDFBFF)
val LightSurfaceDim = Color(0xFFDAD9DD)
val LightSurfaceContainerLowest = Color(0xFFFFFFFF)
val LightSurfaceContainerLow = Color(0xFFF4F3F7)
val LightSurfaceContainer = Color(0xFFEEEDF1)
val LightSurfaceContainerHigh = Color(0xFFE8E7EB)
val LightSurfaceContainerHighest = Color(0xFFE3E2E6)
val LightInverseSurface = Color(0xFF303034)
val LightInverseOnSurface = Color(0xFFF2F0F4)
val LightInversePrimary = Color(0xFFA1C9FF)
val LightError = Color(0xFFBA1A1A)
val LightOnError = Color(0xFFFFFFFF)
val LightErrorContainer = Color(0xFFFFDAD6)
val LightOnErrorContainer = Color(0xFF410002)
val LightOutline = Color(0xFF74777F)
val LightOutlineVariant = Color(0xFFC4C6CF)
val LightScrim = Color(0xFF000000)

// Dark Theme Colors
val DarkPrimary = Color(0xFFA1C9FF)
val DarkOnPrimary = Color(0xFF00325B)
val DarkPrimaryContainer = Color(0xFF00497E)
val DarkOnPrimaryContainer = Color(0xFFD1E4FF)
val DarkSecondary = Color(0xFFBBC7DB)
val DarkOnSecondary = Color(0xFF253140)
val DarkTertiary = Color(0xFFD6BEE4)
val DarkOnTertiary = Color(0xFF3B2948)
val DarkBackground = Color(0xFF111315)
val DarkSurface = Color(0xFF1E2123)
val DarkOnBackground = Color(0xFFE2E2E6)
val DarkOnSurface = Color(0xFFE2E2E6)
val DarkSurfaceVariant = Color(0xFF43474E)
val DarkOnSurfaceVariant = Color(0xFFC3C6CF)

// Dark Theme - Additional Material 3 Colors
val DarkSurfaceBright = Color(0xFF38383D)
val DarkSurfaceDim = Color(0xFF111315)
val DarkSurfaceContainerLowest = Color(0xFF0C0C0E)
val DarkSurfaceContainerLow = Color(0xFF1E2123)
val DarkSurfaceContainer = Color(0xFF222325)
val DarkSurfaceContainerHigh = Color(0xFF2D2D2F)
val DarkSurfaceContainerHighest = Color(0xFF383838)
val DarkInverseSurface = Color(0xFFE2E2E6)
val DarkInverseOnSurface = Color(0xFF303034)
val DarkInversePrimary = Color(0xFF0061A4)
val DarkError = Color(0xFFFFB4AB)
val DarkOnError = Color(0xFF690005)
val DarkErrorContainer = Color(0xFF93000A)
val DarkOnErrorContainer = Color(0xFFFFDAD6)
val DarkOutline = Color(0xFF8E9099)
val DarkOutlineVariant = Color(0xFF44474E)
val DarkScrim = Color(0xFF000000)
